module os {
    requires javafx.fxml;
    requires javafx.controls;

    opens com.os.apps to javafx.fxml;
    exports com.os.apps;
    opens com.os.apps.fileApp.application to javafx.fxml;
    exports com.os.apps.fileApp.application;
    opens com.os.apps.fileApp.controller to javafx.fxml;
    exports com.os.apps.fileApp.controller;
    opens com.os.apps.occupancyApp to javafx.fxml;
    exports com.os.apps.occupancyApp;
    opens com.os.apps.helpApp to javafx.fxml;
    exports com.os.apps.helpApp;
    opens com.os.apps.processApp to javafx.fxml;
    exports com.os.apps.processApp;
    opens com.os.apps.systemFileApp to javafx.fxml;
    exports com.os.apps.systemFileApp;
    opens com.os.datas to javafx.fxml;
    exports com.os.datas;
    opens com.os.utility to javafx.fxml;
    exports com.os.utility;
    opens com.os.main to javafx.fxml;
    exports com.os.main;
    opens com.os.utility.fileSystem to javafx.fxml;
    exports com.os.utility.fileSystem;
    opens com.os.utility.uiUtil to javafx.fxml;
    exports com.os.utility.uiUtil;
    opens com.os.utility.processSystem to javafx.fxml;
    exports com.os.utility.processSystem;
    opens com.os.apps.fileApp.fxmls to javafx.fxml;
    opens com.os.apps.fileApp.css to javafx.fxml;
    opens com.os.apps.fileApp.res to javafx.fxml;
    opens com.os.img to javafx.fxml;
    exports com.os.utility.sceneManager;
    opens com.os.utility.sceneManager to javafx.fxml;
    exports com.os;
    opens com.os to javafx.fxml;
    exports com.os.apps.fileApp;
    opens com.os.apps.fileApp to javafx.fxml;
}